version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: entrypoint.sh
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis_broker

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=chat_admin
      - POSTGRES_PASSWORD=chat_admin
      - POSTGRES_DB=chat_db

  redis_broker:
    image: redis:7.0.4
    ports:
      - 6379:6379

    volumes:
      - redis_cache:/var/lib/redis/data/

volumes:
  postgres_data:
  redis_cache: