# Generated by Django 5.0.4 on 2024-04-28 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='chatgroup',
            new_name='chat_group',
        ),
    ]
